---
- hosts: localhost
	gather_facts: no
	vars: 
		ami_id: "ami-09d95fab7fff3776c"
	module_defaults: 
		group/aws:
			profile: auburn  ????
			region: "us-east-1"
	tasks:
		- name: Provision bobs EC2 instance
			ec2: 
				key_name: auburndemo1
				group: Module5-developer-sg
				instance_type: t3.nano
				image: "{{ ami_id }}"
				instance_tags:
					Name: Module5 Bob
					Module: 5
                                        Department: Accounting
				wait: yes
				vpc_subnet_id: "{{ public_subnet.subnet.id }}"
                                assign_public_up: yes
				exact_count: 1
				count_tag: 
					Name: Module5 Bob
                - name: Provision Marys EC2 instance
			ec2:
				key_name: auburndemo1
				group: Module5-developer-sg
				instance_type: t3.nano
				image: "{{ ami_id }}"
				instance_tags:
					Name: Module5 Mary
					Module: 5
                                        Department: Accounting
				wait: yes
				vpc_subnet_id: "{{ public_subnet.subnet.id }}"
                                assign_public_up: yes
				exact_count: 1
				count_tag:
					Name: Module5 Mary
		- name: Provision Sallys EC2 instance
			ec2:
				key_name: auburndemo1
				group: Module5-developer-sg
				instance_type: t3.nano
				image: "{{ ami_id }}"
				instance_tags:
					Name: Module5 Sally
					Module: 5
                                        Department: DevOps
				wait: yes
				vpc_subnet_id: "{{ public_subnet.subnet.id }}"
                                assign_public_up: yes
				exact_count: 1
				count_tag:
					Name: Module5 Sally

