---
all:
  hosts:
     ec2-3-221-160-176.compute-1.amazonaws.com:
     ec2-18-235-1-240.compute-1.amazonaws.com:
  children:
     al2:
         hosts: 
            ec2-3-221-160-176.compute-1.amazonaws.com:
            ec2-18-235-1-240.compute-1.amazonaws.com:
         vars:
            ansible_user: ec2-user
            ansible_python_interpreter: /usr/bin/python
